In [1]:
import os, re, glob, time, cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import shutil
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from numpy import argmax
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import Sequential, Model, load_model
from tensorflow.python.keras import layers
from tensorflow.python.keras.optimizers import SGD, Adam
from tensorflow.python.keras import regularizers
import time
import pandas as pd
base_dir = './excel/' 
print("success")

ImportError: cannot import name 'SGD' from 'tensorflow.python.keras.optimizers' (c:\Users\JH\anaconda3\lib\site-packages\tensorflow\python\keras\optimizers.py)

In [129]:
model = keras.models.Sequential([
    
    keras.layers.Conv2D(16, kernel_size=(5, 5), activation='relu', input_shape=(200, 120, 3)),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(32, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(128, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Flatten(),
    
    keras.layers.Dense(128, activation='relu'),
    # keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.2),      
    keras.layers.Dense(32, activation='softmax'),
])
print("success")

A


In [130]:
tf.__version__

'1.5.0'

In [131]:

model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print("test")

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_29 (Conv2D)           (None, 196, 116, 16)      1216      
_________________________________________________________________
max_pooling2d_29 (MaxPooling (None, 98, 58, 16)        0         
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 96, 56, 32)        4640      
_________________________________________________________________
max_pooling2d_30 (MaxPooling (None, 48, 28, 32)        0         
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 46, 26, 64)        18496     
_________________________________________________________________
max_pooling2d_31 (MaxPooling (None, 23, 13, 64)        0         
_________________________________________________________________
conv2d_32 (Conv2D)           (None, 21, 11, 128)       73856     
__________

In [132]:
groups_folder_pos_path = './pos/'               # './50/RGB_f/'  
groups_folder_rot_path = './rot/'               # './50/Depth_f/' 
categories = ["1L", "1R", "2L", "2R", "3L", "3R", "4L", "4R","5L", "5R", "6L", "6R", "7L", "7R", "8L", "8R","9L", "9R", "10L", "10R", "11L", "11R", "12L", "12R","13L", "13R", "14L", "14R", "15L", "15R", "16L", "16R"]
#categories = ["1L", "1R", "2L", "2R", "3L", "3R", "4L", "4R","5L", "5R", "6L", "6R", "7L", "7R", "8L", "8R"]
#categories = ["1L", "2L",  "3L", "4L", "5L", "6L",  "7L",  "8L"]
num_classes = len(categories)
len(categories)

32

In [133]:
# image_w = 120
# image_h = 200
# image_dir_pos = groups_folder_pos_path + '1R' + '/'
# pos = cv2.imread(image_dir_pos +'1-1-1.png')

# pos = cv2.resize(pos, dsize=(image_w, image_h))
# pos = pos/256
# pos = np.float16(pos)
# # pos = cv2.resize(pos, dsize=(image_w, image_h))
# # pos = np.array(pos,dtype = np.float16)

# # plt.imshow(pos)
# print(pos)
# print(pos.dtype)

In [1]:
image_w = 120
image_h = 200
  
X = []
Y = []
test = 0
for idex, categorie in enumerate(categories):
    label = [0 for i in range(num_classes)]
    label[idex] = 1
    image_dir_pos = groups_folder_pos_path + categorie + '/'
    image_dir_rot = groups_folder_rot_path + categorie + '/'


    for top, dir, f in os.walk(image_dir_pos):
        
        for filename in f:
            try:
                pos = cv2.imread(image_dir_pos +filename)
                print(pos.shape)
                pos = cv2.resize(pos, dsize=(image_w, image_h))
                img = pos
                img =  img/256
                img = np.float16(img)
                X.append(img)
                Y.append(label)
            except:
                print("FAIL PLEASE")
                print(groups_folder_pos_path + categorie + filename)

X = np.array(X)
Y = np.array(Y)
print(num_classes)
print(X.shape)
print(Y.shape)
print("finish")

NameError: name 'categories' is not defined

In [136]:
# x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3 ,shuffle=True)
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3 ,shuffle=True, stratify = Y )


print(x_train.shape)
print(Y.shape)
print(y_test.shape)

A
(5374, 200, 120, 3)
(7678, 32)
(2304, 32)


In [138]:
skf = KFold(n_splits=5, shuffle=True)
accuracy=[]
for train, validation in skf.split(x_train, y_train):
    print(train.shape)
    print(x_train[train].shape)
    model.fit(x_train[train], y_train[train], epochs=20, batch_size = 16) #epoch = 20  batch_size = 16
    print("test")
    k_accuracy = '%.4f' % (model.evaluate(x_train[validation], y_train[validation])[1])
    accuracy.append(k_accuracy)

print('\nK-fold cross validation Accuracy: {}'.format(accuracy))

(4299,)
(4299, 200, 120, 3)
Epoch 1/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 1.8242 - acc: 0.4475

Epoch 2/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.6112 - acc: 0.7967

Epoch 3/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.3742 - acc: 0.8728

Epoch 4/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.2628 - acc: 0.9049

Epoch 5/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.2006 - acc: 0.9265

Epoch 6/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.1569 - acc: 0.9488

Epoch 7/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 

In [140]:
start = time.time()
test_loss, test_acc = model.evaluate(x_test,  y_test, verbose=1)
predict = model.predict_classes(x_test)
print("TIME is ", time.time()-start)
print('\n테스트 정확도:', test_acc)
print(len(predict))

2304/2304 [==============================]2304/2304 [==============================] - 11s 5ms/step

TIME is  22.508829832077026

테스트 정확도: 0.96484375
2304


In [144]:
f = open('class4.txt','w')
f2 = open('predict4.txt','w')
print(y_test)
print(len(y_test))
for i in range(len(y_test)):
    print("Class : " + str(categories[y_test[i].argmax()]) + ", Predict : "+ str(categories[predict[i]]))
    f.write(str(categories[y_test[i].argmax()]))
    f.write('\n')
    f2.write(str(categories[predict[i]]))
    f2.write('\n')
  

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2304


In [ ]:
np.save('./testset/x_test', x_test) # x_save.npy
np.save('./testset/y_test', y_test) # x_save.npy
np.save('./testset/xcg_test', xcg_test) # x_save.npy
np.save('./testset/ycg_test', ycg_test) # x_save.npy
np.save('./testset/xtotal_test', xtotal_test) # x_save.npy
np.save('./testset/ytotal_test', ytotal_test) # x_save.npy
