In [128]:
import os, re, glob, time, cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import shutil
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from numpy import argmax
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import Sequential, Model, load_model
from tensorflow.python.keras import layers
from tensorflow.python.keras.optimizers import SGD, Adam
from tensorflow.python.keras import regularizers
import time
import pandas as pd
base_dir = './excel/' 
print("success")

A


In [129]:
model = keras.models.Sequential([
    
    keras.layers.Conv2D(16, kernel_size=(5, 5), activation='relu', input_shape=(200, 120, 3)),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(32, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Conv2D(128, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D(pool_size=(2, 2)),
    keras.layers.Flatten(),
    
    keras.layers.Dense(128, activation='relu'),
    # keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.2),      
    keras.layers.Dense(32, activation='softmax'),
])
print("success")

A


In [130]:
tf.__version__

'1.5.0'

In [131]:

model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print("test")

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_29 (Conv2D)           (None, 196, 116, 16)      1216      
_________________________________________________________________
max_pooling2d_29 (MaxPooling (None, 98, 58, 16)        0         
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 96, 56, 32)        4640      
_________________________________________________________________
max_pooling2d_30 (MaxPooling (None, 48, 28, 32)        0         
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 46, 26, 64)        18496     
_________________________________________________________________
max_pooling2d_31 (MaxPooling (None, 23, 13, 64)        0         
_________________________________________________________________
conv2d_32 (Conv2D)           (None, 21, 11, 128)       73856     
__________

In [132]:
groups_folder_pos_path = './pos/'               # './50/RGB_f/'  
groups_folder_rot_path = './rot/'               # './50/Depth_f/' 
categories = ["1L", "1R", "2L", "2R", "3L", "3R", "4L", "4R","5L", "5R", "6L", "6R", "7L", "7R", "8L", "8R","9L", "9R", "10L", "10R", "11L", "11R", "12L", "12R","13L", "13R", "14L", "14R", "15L", "15R", "16L", "16R"]
#categories = ["1L", "1R", "2L", "2R", "3L", "3R", "4L", "4R","5L", "5R", "6L", "6R", "7L", "7R", "8L", "8R"]
#categories = ["1L", "2L",  "3L", "4L", "5L", "6L",  "7L",  "8L"]
num_classes = len(categories)
len(categories)

32

In [133]:
# image_w = 120
# image_h = 200
# image_dir_pos = groups_folder_pos_path + '1R' + '/'
# pos = cv2.imread(image_dir_pos +'1-1-1.png')

# pos = cv2.resize(pos, dsize=(image_w, image_h))
# pos = pos/256
# pos = np.float16(pos)
# # pos = cv2.resize(pos, dsize=(image_w, image_h))
# # pos = np.array(pos,dtype = np.float16)

# # plt.imshow(pos)
# print(pos)
# print(pos.dtype)

In [134]:
image_w = 120
image_h = 200
  
X = []
Y = []
test = 0
for idex, categorie in enumerate(categories):
    label = [0 for i in range(num_classes)]
    label[idex] = 1
    image_dir_pos = groups_folder_pos_path + categorie + '/'
    image_dir_rot = groups_folder_rot_path + categorie + '/'


    for top, dir, f in os.walk(image_dir_pos):
        
        for filename in f:
            try:
                pos = cv2.imread(image_dir_pos +filename)
                print(pos.shape)
                pos = cv2.resize(pos, dsize=(image_w, image_h))
                img = pos
                img =  img/256
                img = np.float16(img)
                X.append(img)
                Y.append(label)
            except:
                print("FAIL PLEASE")
                print(groups_folder_pos_path + categorie + filename)

X = np.array(X)
Y = np.array(Y)
print(num_classes)
print(X.shape)
print(Y.shape)
print("finish")

(446, 24, 3)
(495, 24, 3)
(370, 24, 3)
(442, 24, 3)
(329, 24, 3)
(356, 24, 3)
(407, 24, 3)
(254, 24, 3)
(334, 24, 3)
(260, 24, 3)
(217, 24, 3)
(263, 24, 3)
(212, 24, 3)
(365, 24, 3)
(319, 24, 3)
(335, 24, 3)
(315, 24, 3)
(341, 24, 3)
(296, 24, 3)
(377, 24, 3)
(273, 24, 3)
(437, 24, 3)
(350, 24, 3)
(432, 24, 3)
(317, 24, 3)
(406, 24, 3)
(622, 24, 3)
(427, 24, 3)
(448, 24, 3)
(526, 24, 3)
(376, 24, 3)
(493, 24, 3)
(527, 24, 3)
(611, 24, 3)
(536, 24, 3)
(580, 24, 3)
(586, 24, 3)
(448, 24, 3)
(443, 24, 3)
(807, 24, 3)
(342, 24, 3)
(255, 24, 3)
(361, 24, 3)
(546, 24, 3)
(397, 24, 3)
(469, 24, 3)
(630, 24, 3)
(490, 24, 3)
(417, 24, 3)
(451, 24, 3)
(415, 24, 3)
(428, 24, 3)
(287, 24, 3)
(724, 24, 3)
(542, 24, 3)
(554, 24, 3)
(547, 24, 3)
(555, 24, 3)
(538, 24, 3)
(501, 24, 3)
(478, 24, 3)
(563, 24, 3)
(438, 24, 3)
(252, 24, 3)
(396, 24, 3)
(385, 24, 3)
(603, 24, 3)
(407, 24, 3)
(463, 24, 3)
(388, 24, 3)
(349, 24, 3)
(378, 24, 3)
(420, 24, 3)
(365, 24, 3)
(348, 24, 3)
(386, 24, 3)
(406, 24, 3)

(370, 24, 3)
(286, 24, 3)
(292, 24, 3)
(292, 24, 3)
(302, 24, 3)
(346, 24, 3)
(374, 24, 3)
(272, 24, 3)
(411, 24, 3)
(401, 24, 3)
(419, 24, 3)
(394, 24, 3)
(396, 24, 3)
(398, 24, 3)
(353, 24, 3)
(293, 24, 3)
(330, 24, 3)
(401, 24, 3)
(437, 24, 3)
(315, 24, 3)
(277, 24, 3)
(284, 24, 3)
(287, 24, 3)
(253, 24, 3)
(329, 24, 3)
(266, 24, 3)
(306, 24, 3)
(272, 24, 3)
(144, 24, 3)
(363, 24, 3)
(453, 24, 3)
(261, 24, 3)
(128, 24, 3)
(246, 24, 3)
(135, 24, 3)
(277, 24, 3)
(334, 24, 3)
(282, 24, 3)
(310, 24, 3)
(293, 24, 3)
(345, 24, 3)
(411, 24, 3)
(436, 24, 3)
(311, 24, 3)
(426, 24, 3)
(438, 24, 3)
(363, 24, 3)
(398, 24, 3)
(371, 24, 3)
(371, 24, 3)
(521, 24, 3)
(421, 24, 3)
(441, 24, 3)
(490, 24, 3)
(448, 24, 3)
(403, 24, 3)
(379, 24, 3)
(393, 24, 3)
(366, 24, 3)
(288, 24, 3)
(309, 24, 3)
(279, 24, 3)
(296, 24, 3)
(260, 24, 3)
(355, 24, 3)
(418, 24, 3)
(338, 24, 3)
(284, 24, 3)
(382, 24, 3)
(287, 24, 3)
(400, 24, 3)
(284, 24, 3)
(407, 24, 3)
(393, 24, 3)
(384, 24, 3)
(411, 24, 3)
(496, 24, 3)

(413, 24, 3)
(479, 24, 3)
(325, 24, 3)
(338, 24, 3)
(314, 24, 3)
(365, 24, 3)
(314, 24, 3)
(371, 24, 3)
(336, 24, 3)
(311, 24, 3)
(376, 24, 3)
(304, 24, 3)
(359, 24, 3)
(340, 24, 3)
(353, 24, 3)
(350, 24, 3)
(395, 24, 3)
(308, 24, 3)
(402, 24, 3)
(338, 24, 3)
(330, 24, 3)
(409, 24, 3)
(478, 24, 3)
(225, 24, 3)
(463, 24, 3)
(284, 24, 3)
(430, 24, 3)
(172, 24, 3)
(451, 24, 3)
(507, 24, 3)
(474, 24, 3)
(292, 24, 3)
(441, 24, 3)
(486, 24, 3)
(407, 24, 3)
(393, 24, 3)
(503, 24, 3)
(473, 24, 3)
(510, 24, 3)
(437, 24, 3)
(504, 24, 3)
(415, 24, 3)
(420, 24, 3)
(308, 24, 3)
(432, 24, 3)
(456, 24, 3)
(509, 24, 3)
(417, 24, 3)
(475, 24, 3)
(560, 24, 3)
(530, 24, 3)
(530, 24, 3)
(538, 24, 3)
(554, 24, 3)
(297, 24, 3)
(443, 24, 3)
(490, 24, 3)
(433, 24, 3)
(417, 24, 3)
(451, 24, 3)
(396, 24, 3)
(434, 24, 3)
(383, 24, 3)
(403, 24, 3)
(363, 24, 3)
(328, 24, 3)
(371, 24, 3)
(375, 24, 3)
(419, 24, 3)
(401, 24, 3)
(453, 24, 3)
(375, 24, 3)
(443, 24, 3)
(432, 24, 3)
(520, 24, 3)
(510, 24, 3)
(294, 24, 3)

(380, 24, 3)
(402, 24, 3)
(391, 24, 3)
(386, 24, 3)
(377, 24, 3)
(432, 24, 3)
(402, 24, 3)
(367, 24, 3)
(348, 24, 3)
(423, 24, 3)
(208, 24, 3)
(270, 24, 3)
(308, 24, 3)
(382, 24, 3)
(354, 24, 3)
(333, 24, 3)
(369, 24, 3)
(292, 24, 3)
(317, 24, 3)
(342, 24, 3)
(297, 24, 3)
(295, 24, 3)
(318, 24, 3)
(342, 24, 3)
(335, 24, 3)
(502, 24, 3)
(541, 24, 3)
(261, 24, 3)
(360, 24, 3)
(442, 24, 3)
(411, 24, 3)
(373, 24, 3)
(481, 24, 3)
(483, 24, 3)
(620, 24, 3)
(533, 24, 3)
(574, 24, 3)
(443, 24, 3)
(560, 24, 3)
(437, 24, 3)
(332, 24, 3)
(659, 24, 3)
(544, 24, 3)
(441, 24, 3)
(536, 24, 3)
(465, 24, 3)
(510, 24, 3)
(593, 24, 3)
(401, 24, 3)
(468, 24, 3)
(425, 24, 3)
(379, 24, 3)
(388, 24, 3)
(436, 24, 3)
(472, 24, 3)
(419, 24, 3)
(400, 24, 3)
(411, 24, 3)
(428, 24, 3)
(474, 24, 3)
(390, 24, 3)
(41, 24, 3)
(291, 24, 3)
(355, 24, 3)
(326, 24, 3)
(374, 24, 3)
(295, 24, 3)
(420, 24, 3)
(309, 24, 3)
(308, 24, 3)
(322, 24, 3)
(364, 24, 3)
(315, 24, 3)
(298, 24, 3)
(336, 24, 3)
(378, 24, 3)
(383, 24, 3)


(425, 24, 3)
(370, 24, 3)
(263, 24, 3)
(310, 24, 3)
(278, 24, 3)
(318, 24, 3)
(448, 24, 3)
(287, 24, 3)
(409, 24, 3)
(444, 24, 3)
(397, 24, 3)
(417, 24, 3)
(415, 24, 3)
(399, 24, 3)
(310, 24, 3)
(280, 24, 3)
(294, 24, 3)
(397, 24, 3)
(262, 24, 3)
(349, 24, 3)
(268, 24, 3)
(260, 24, 3)
(172, 24, 3)
(186, 24, 3)
(183, 24, 3)
(173, 24, 3)
(156, 24, 3)
(222, 24, 3)
(350, 24, 3)
(137, 24, 3)
(148, 24, 3)
(207, 24, 3)
(154, 24, 3)
(219, 24, 3)
(370, 24, 3)
(298, 24, 3)
(321, 24, 3)
(285, 24, 3)
(310, 24, 3)
(327, 24, 3)
(282, 24, 3)
(481, 24, 3)
(337, 24, 3)
(419, 24, 3)
(386, 24, 3)
(334, 24, 3)
(370, 24, 3)
(449, 24, 3)
(404, 24, 3)
(467, 24, 3)
(222, 24, 3)
(394, 24, 3)
(450, 24, 3)
(383, 24, 3)
(260, 24, 3)
(271, 24, 3)
(311, 24, 3)
(249, 24, 3)
(262, 24, 3)
(204, 24, 3)
(291, 24, 3)
(370, 24, 3)
(318, 24, 3)
(284, 24, 3)
(315, 24, 3)
(265, 24, 3)
(304, 24, 3)
(428, 24, 3)
(390, 24, 3)
(437, 24, 3)
(364, 24, 3)
(425, 24, 3)
(219, 24, 3)
(355, 24, 3)
(457, 24, 3)
(349, 24, 3)
(438, 24, 3)

(371, 24, 3)
(396, 24, 3)
(493, 24, 3)
(495, 24, 3)
(458, 24, 3)
(432, 24, 3)
(485, 24, 3)
(521, 24, 3)
(606, 24, 3)
(494, 24, 3)
(528, 24, 3)
(339, 24, 3)
(562, 24, 3)
(598, 24, 3)
(498, 24, 3)
(437, 24, 3)
(455, 24, 3)
(421, 24, 3)
(430, 24, 3)
(390, 24, 3)
(479, 24, 3)
(506, 24, 3)
(453, 24, 3)
(574, 24, 3)
(362, 24, 3)
(511, 24, 3)
(500, 24, 3)
(431, 24, 3)
(495, 24, 3)
(447, 24, 3)
(469, 24, 3)
(483, 24, 3)
(510, 24, 3)
(527, 24, 3)
(500, 24, 3)
(405, 24, 3)
(525, 24, 3)
(528, 24, 3)
(479, 24, 3)
(483, 24, 3)
(503, 24, 3)
(476, 24, 3)
(537, 24, 3)
(463, 24, 3)
(460, 24, 3)
(443, 24, 3)
(372, 24, 3)
(432, 24, 3)
(426, 24, 3)
(509, 24, 3)
(479, 24, 3)
(550, 24, 3)
(570, 24, 3)
(460, 24, 3)
(535, 24, 3)
(477, 24, 3)
(448, 24, 3)
(328, 24, 3)
(412, 24, 3)
(466, 24, 3)
(508, 24, 3)
(446, 24, 3)
(438, 24, 3)
(346, 24, 3)
(370, 24, 3)
(331, 24, 3)
(318, 24, 3)
(436, 24, 3)
(403, 24, 3)
(464, 24, 3)
(530, 24, 3)
(342, 24, 3)
(491, 24, 3)
(495, 24, 3)
(482, 24, 3)
(442, 24, 3)
(449, 24, 3)

(370, 24, 3)
(383, 24, 3)
(360, 24, 3)
(376, 24, 3)
(340, 24, 3)
(330, 24, 3)
(357, 24, 3)
(351, 24, 3)
(382, 24, 3)
(340, 24, 3)
(599, 24, 3)
(535, 24, 3)
(387, 24, 3)
(467, 24, 3)
(462, 24, 3)
(394, 24, 3)
(410, 24, 3)
(546, 24, 3)
(555, 24, 3)
(460, 24, 3)
(440, 24, 3)
(468, 24, 3)
(490, 24, 3)
(409, 24, 3)
(442, 24, 3)
(389, 24, 3)
(305, 24, 3)
(507, 24, 3)
(264, 24, 3)
(444, 24, 3)
(544, 24, 3)
(688, 24, 3)
(458, 24, 3)
(572, 24, 3)
(430, 24, 3)
(576, 24, 3)
(492, 24, 3)
(357, 24, 3)
(411, 24, 3)
(412, 24, 3)
(419, 24, 3)
(406, 24, 3)
(420, 24, 3)
(391, 24, 3)
(551, 24, 3)
(494, 24, 3)
(422, 24, 3)
(438, 24, 3)
(301, 24, 3)
(426, 24, 3)
(468, 24, 3)
(440, 24, 3)
(329, 24, 3)
(401, 24, 3)
(322, 24, 3)
(437, 24, 3)
(402, 24, 3)
(489, 24, 3)
(531, 24, 3)
(353, 24, 3)
(525, 24, 3)
(417, 24, 3)
(441, 24, 3)
(277, 24, 3)
(289, 24, 3)
(329, 24, 3)
(322, 24, 3)
(328, 24, 3)
(427, 24, 3)
(352, 24, 3)
(292, 24, 3)
(514, 24, 3)
(334, 24, 3)
(553, 24, 3)
(416, 24, 3)
(415, 24, 3)
(529, 24, 3)

(439, 24, 3)
(287, 24, 3)
(355, 24, 3)
(297, 24, 3)
(367, 24, 3)
(331, 24, 3)
(546, 24, 3)
(305, 24, 3)
(544, 24, 3)
(468, 24, 3)
(377, 24, 3)
(426, 24, 3)
(388, 24, 3)
(445, 24, 3)
(514, 24, 3)
(392, 24, 3)
(467, 24, 3)
(318, 24, 3)
(419, 24, 3)
(459, 24, 3)
(438, 24, 3)
(312, 24, 3)
(287, 24, 3)
(298, 24, 3)
(233, 24, 3)
(329, 24, 3)
(259, 24, 3)
(330, 24, 3)
(343, 24, 3)
(409, 24, 3)
(310, 24, 3)
(380, 24, 3)
(298, 24, 3)
(373, 24, 3)
(485, 24, 3)
(462, 24, 3)
(507, 24, 3)
(483, 24, 3)
(497, 24, 3)
(274, 24, 3)
(427, 24, 3)
(475, 24, 3)
(435, 24, 3)
(434, 24, 3)
(410, 24, 3)
(403, 24, 3)
(453, 24, 3)
(460, 24, 3)
(461, 24, 3)
(424, 24, 3)
(330, 24, 3)
(670, 24, 3)
(360, 24, 3)
(435, 24, 3)
(478, 24, 3)
(361, 24, 3)
(527, 24, 3)
(407, 24, 3)
(448, 24, 3)
(409, 24, 3)
(386, 24, 3)
(411, 24, 3)
(290, 24, 3)
(379, 24, 3)
(358, 24, 3)
(275, 24, 3)
(345, 24, 3)
(272, 24, 3)
(309, 24, 3)
(322, 24, 3)
(325, 24, 3)
(321, 24, 3)
(357, 24, 3)
(319, 24, 3)
(397, 24, 3)
(365, 24, 3)
(361, 24, 3)

(370, 24, 3)
(571, 24, 3)
(465, 24, 3)
(565, 24, 3)
(492, 24, 3)
(488, 24, 3)
(287, 24, 3)
(493, 24, 3)
(375, 24, 3)
(467, 24, 3)
(406, 24, 3)
(483, 24, 3)
(427, 24, 3)
(434, 24, 3)
(374, 24, 3)
(394, 24, 3)
(400, 24, 3)
(308, 24, 3)
(392, 24, 3)
(450, 24, 3)
(380, 24, 3)
(343, 24, 3)
(351, 24, 3)
(345, 24, 3)
(389, 24, 3)
(365, 24, 3)
(405, 24, 3)
(423, 24, 3)
(285, 24, 3)
(499, 24, 3)
(587, 24, 3)
(498, 24, 3)
(572, 24, 3)
(495, 24, 3)
(376, 24, 3)
(398, 24, 3)
(375, 24, 3)
(450, 24, 3)
(407, 24, 3)
(315, 24, 3)
(461, 24, 3)
(275, 24, 3)
(320, 24, 3)
(267, 24, 3)
(286, 24, 3)
(247, 24, 3)
(329, 24, 3)
(316, 24, 3)
(402, 24, 3)
(408, 24, 3)
(400, 24, 3)
(430, 24, 3)
(420, 24, 3)
(398, 24, 3)
(312, 24, 3)
(282, 24, 3)
(358, 24, 3)
(351, 24, 3)
(264, 24, 3)
(279, 24, 3)
(275, 24, 3)
(239, 24, 3)
(234, 24, 3)
(227, 24, 3)
(274, 24, 3)
(248, 24, 3)
(270, 24, 3)
(260, 24, 3)
(349, 24, 3)
(217, 24, 3)
(277, 24, 3)
(216, 24, 3)
(200, 24, 3)
(207, 24, 3)
(307, 24, 3)
(369, 24, 3)
(293, 24, 3)

(343, 24, 3)
(405, 24, 3)
(360, 24, 3)
(333, 24, 3)
(412, 24, 3)
(460, 24, 3)
(550, 24, 3)
(477, 24, 3)
(559, 24, 3)
(364, 24, 3)
(536, 24, 3)
(413, 24, 3)
(443, 24, 3)
(471, 24, 3)
(353, 24, 3)
(428, 24, 3)
(475, 24, 3)
(480, 24, 3)
(516, 24, 3)
(458, 24, 3)
(408, 24, 3)
(443, 24, 3)
(383, 24, 3)
(410, 24, 3)
(488, 24, 3)
(369, 24, 3)
(409, 24, 3)
(349, 24, 3)
(382, 24, 3)
(375, 24, 3)
(390, 24, 3)
(475, 24, 3)
(459, 24, 3)
(473, 24, 3)
(454, 24, 3)
(408, 24, 3)
(351, 24, 3)
(400, 24, 3)
(325, 24, 3)
(314, 24, 3)
(314, 24, 3)
(318, 24, 3)
(291, 24, 3)
(316, 24, 3)
(296, 24, 3)
(593, 24, 3)
(274, 24, 3)
(338, 24, 3)
(487, 24, 3)
(337, 24, 3)
(673, 24, 3)
(504, 24, 3)
(451, 24, 3)
(428, 24, 3)
(454, 24, 3)
(488, 24, 3)
(430, 24, 3)
(550, 24, 3)
(357, 24, 3)
(527, 24, 3)
(472, 24, 3)
(474, 24, 3)
(496, 24, 3)
(432, 24, 3)
(430, 24, 3)
(421, 24, 3)
(398, 24, 3)
(505, 24, 3)
(398, 24, 3)
(364, 24, 3)
(440, 24, 3)
(278, 24, 3)
(390, 24, 3)
(309, 24, 3)
(682, 24, 3)
(552, 24, 3)
(591, 24, 3)

(284, 24, 3)
(250, 24, 3)
(397, 24, 3)
(462, 24, 3)
(434, 24, 3)
(398, 24, 3)
(432, 24, 3)
(393, 24, 3)
(459, 24, 3)
(616, 24, 3)
(570, 24, 3)
(606, 24, 3)
(605, 24, 3)
(613, 24, 3)
(445, 24, 3)
(545, 24, 3)
(576, 24, 3)
(510, 24, 3)
(596, 24, 3)
(570, 24, 3)
(569, 24, 3)
(563, 24, 3)
(615, 24, 3)
(522, 24, 3)
(428, 24, 3)
(487, 24, 3)
(544, 24, 3)
(598, 24, 3)
(462, 24, 3)
(572, 24, 3)
(462, 24, 3)
(483, 24, 3)
(452, 24, 3)
(546, 24, 3)
(473, 24, 3)
(496, 24, 3)
(467, 24, 3)
(509, 24, 3)
(464, 24, 3)
(551, 24, 3)
(480, 24, 3)
(574, 24, 3)
(492, 24, 3)
(503, 24, 3)
(481, 24, 3)
(484, 24, 3)
(493, 24, 3)
(557, 24, 3)
(539, 24, 3)
(553, 24, 3)
(550, 24, 3)
(555, 24, 3)
(457, 24, 3)
(591, 24, 3)
(536, 24, 3)
(760, 24, 3)
(744, 24, 3)
(815, 24, 3)
(838, 24, 3)
(673, 24, 3)
(682, 24, 3)
(567, 24, 3)
(530, 24, 3)
(453, 24, 3)
(511, 24, 3)
(447, 24, 3)
(472, 24, 3)
(430, 24, 3)
(562, 24, 3)
(547, 24, 3)
(576, 24, 3)
(562, 24, 3)
(425, 24, 3)
(572, 24, 3)
(526, 24, 3)
(514, 24, 3)
(677, 24, 3)

(516, 24, 3)
(963, 24, 3)
(546, 24, 3)
(511, 24, 3)
(529, 24, 3)
(534, 24, 3)
(573, 24, 3)
(577, 24, 3)
(601, 24, 3)
(597, 24, 3)
(685, 24, 3)
(537, 24, 3)
(548, 24, 3)
(669, 24, 3)
(598, 24, 3)
(561, 24, 3)
(674, 24, 3)
(533, 24, 3)
(310, 24, 3)
(290, 24, 3)
(655, 24, 3)
(527, 24, 3)
(268, 24, 3)
(432, 24, 3)
(488, 24, 3)
(498, 24, 3)
(554, 24, 3)
(541, 24, 3)
(573, 24, 3)
(553, 24, 3)
(544, 24, 3)
(611, 24, 3)
(724, 24, 3)
(530, 24, 3)
(912, 24, 3)
(622, 24, 3)
(622, 24, 3)
(628, 24, 3)
(599, 24, 3)
(656, 24, 3)
(667, 24, 3)
(632, 24, 3)
(682, 24, 3)
(646, 24, 3)
(526, 24, 3)
(182, 24, 3)
(730, 24, 3)
(605, 24, 3)
(618, 24, 3)
(536, 24, 3)
(576, 24, 3)
(572, 24, 3)
(594, 24, 3)
(572, 24, 3)
(613, 24, 3)
(599, 24, 3)
(876, 24, 3)
(760, 24, 3)
(784, 24, 3)
(748, 24, 3)
(930, 24, 3)
(573, 24, 3)
(598, 24, 3)
(833, 24, 3)
(707, 24, 3)
(757, 24, 3)
(680, 24, 3)
(635, 24, 3)
(661, 24, 3)
(684, 24, 3)
(855, 24, 3)
(760, 24, 3)
(782, 24, 3)
(648, 24, 3)
(566, 24, 3)
(701, 24, 3)
(555, 24, 3)

In [136]:
# x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3 ,shuffle=True)
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3 ,shuffle=True, stratify = Y )


print(x_train.shape)
print(Y.shape)
print(y_test.shape)

A
(5374, 200, 120, 3)
(7678, 32)
(2304, 32)


In [138]:
skf = KFold(n_splits=5, shuffle=True)
accuracy=[]
for train, validation in skf.split(x_train, y_train):
    print(train.shape)
    print(x_train[train].shape)
    model.fit(x_train[train], y_train[train], epochs=20, batch_size = 16) #epoch = 20  batch_size = 16
    print("test")
    k_accuracy = '%.4f' % (model.evaluate(x_train[validation], y_train[validation])[1])
    accuracy.append(k_accuracy)

print('\nK-fold cross validation Accuracy: {}'.format(accuracy))

(4299,)
(4299, 200, 120, 3)
Epoch 1/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 1.8242 - acc: 0.4475

Epoch 2/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.6112 - acc: 0.7967

Epoch 3/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.3742 - acc: 0.8728

Epoch 4/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.2628 - acc: 0.9049

Epoch 5/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.2006 - acc: 0.9265

Epoch 6/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 0.1569 - acc: 0.9488

Epoch 7/20
4299/4299 [==============================]4299/4299 [==============================] - 68s 16ms/step - loss: 

In [140]:
start = time.time()
test_loss, test_acc = model.evaluate(x_test,  y_test, verbose=1)
predict = model.predict_classes(x_test)
print("TIME is ", time.time()-start)
print('\n테스트 정확도:', test_acc)
print(len(predict))

2304/2304 [==============================]2304/2304 [==============================] - 11s 5ms/step

TIME is  22.508829832077026

테스트 정확도: 0.96484375
2304


In [144]:
f = open('class4.txt','w')
f2 = open('predict4.txt','w')
print(y_test)
print(len(y_test))
for i in range(len(y_test)):
    print("Class : " + str(categories[y_test[i].argmax()]) + ", Predict : "+ str(categories[predict[i]]))
    f.write(str(categories[y_test[i].argmax()]))
    f.write('\n')
    f2.write(str(categories[predict[i]]))
    f2.write('\n')
  

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2304


In [ ]:
np.save('./testset/x_test', x_test) # x_save.npy
np.save('./testset/y_test', y_test) # x_save.npy
np.save('./testset/xcg_test', xcg_test) # x_save.npy
np.save('./testset/ycg_test', ycg_test) # x_save.npy
np.save('./testset/xtotal_test', xtotal_test) # x_save.npy
np.save('./testset/ytotal_test', ytotal_test) # x_save.npy
